### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by xmqhzs** [TheDawnCc/Steganography#2]
打开任何图片PNG，JPG都会直接闪退。尝试过管理员模式打开，也尝试过WIN7兼容模式，依然打开图片软件是死掉。源码可正常编译，但是无论是重新编译过的源码，还是源码自带的已编译好的程序，都一样，打开图片就死。应该不是系统问题，我重装过两个版本的WIN10都是微软正版的，家庭版与专业版均无法使用软件

**Comment by TheDawnCc** [comment]
有正确安装EmguCV并引用吗?因为程序当初没做异步的处理,打开图片做dft跟dct的预处理可能会耗时比较长,可能会出现假死现象

**Comment by xmqhzs** [comment]
> 
> 
> 有正确安装EmguCV并引用吗?因为程序当初没做异步的处理,打开图片做dft跟dct的预处理可能会耗时比较长,可能会出现假死现象

有正确安装并引用，你的源码中也有编译好的程序，尝试过一样闪退。打开图片确实是会假死一下，但假死后就直接闪退了。我非常喜欢这个软件，希望您能够处理一下这个问题，万分感谢。

**Comment by TheDawnCc** [comment]
你能把你打开的图片发给我吗?我看下是不是程序的问题

**Comment by xmqhzs** [comment]
> 
> 
> 你能把你打开的图片发给我吗?我看下是不是程序的问题

我是随意打开任何图片都闪退啊，JPG和PNG都换过多张尝试过。

**Comment by TheDawnCc** [comment]
你那边编译能在debug模式下看到是哪里出了问题造成的闪退吗?

**Comment by xmqhzs** [comment]
> 
> 
> 你那边编译能在debug模式下看到是哪里出了问题造成的闪退吗?

我刚刚在debug模式下试了一下，貌似是emgu的问题，但是源码中引用的emgu都是正常的，这是为什么啊？

**Comment by xmqhzs** [comment]
> 
> 
> 你那边编译能在debug模式下看到是哪里出了问题造成的闪退吗?

System.TypeInitializationException:““Emgu.CV.CvInvoke”的类型初始值设定项引发异常。”
内部异常
DllNotFoundException: 无法加载 DLL“cvextern”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。

**Comment by xmqhzs** [comment]
能不能发布个编译好的版本啊，我实在搞不定这个问题。

> 
> 
> 你那边编译能在debug模式下看到是哪里出了问题造成的闪退吗?

能不能麻烦你发布个编译好的版本啊，我弄了好久实在搞不定这个问题。

**Comment by TheDawnCc** [comment]
是的,这个框架的引用有点问题,我当初也折腾了很久,我重新发了readme附加了emgucv的下载地址,下载安装完emgucv后要把bin/x64文件夹复制到程序的debug目录下

**Comment by TheDawnCc** [comment]
编译好的版本太大了,程序能有1个G还多,你下好emgucv然后复制dll到debug目录下试试吧

**Comment by xmqhzs** [comment]
> 
> 
> 编译好的版本太大了,程序能有1个G还多,你下好emgucv然后复制dll到debug目录下试试吧

谢谢，我按此方法尝试一下

**Comment by TheDawnCc** [comment]
我将EmguCV改为Nuget引用了,你可以同步下看看能不能用了

**Comment by TheDawnCc** [comment]
我将EmguCV框架改为Nuget管理了,你可以重新同步下看看还有问题吗

**Comment by xmqhzs** [comment]
> 
> 
> 我将EmguCV框架改为Nuget管理了,你可以重新同步下看看还有问题吗

搞定，万分感谢！

**Comment by xmqhzs** [comment]
> 
> 
> 我将EmguCV框架改为Nuget管理了,你可以重新同步下看看还有问题吗

PreView 是干嘛用的，打开弹出的窗口是一片灰色的，什么都没有。然后就会卡住很久也没反应

**Comment by TheDawnCc** [comment]
preview是进行水印加密和预览加密后的图片的,选用dct或者dft计算量会比较大可能会卡住
